# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Wydanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('data_wydania', models.DateField()),
                ('liczba_stron', models.IntegerField()),
                ('wydawnictwo', models.CharField(max_length=350)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Ksiazka')),
            ],
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='wydanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Wydanie'),
        ),
    ]
