# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170109_1121'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=150)),
                ('nazwisko', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='autorzy',
            field=models.ManyToManyField(to='book.Autor'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='kategorie',
            field=models.ManyToManyField(to='book.Kategoria'),
        ),
    ]
