# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170109_1121'),
        ('book', '0002_auto_20170117_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.IntegerField()),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SiteUser')),
                ('wydanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Wydanie')),
            ],
        ),
        migrations.CreateModel(
            name='Polka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SiteUser')),
                ('wydania', models.ManyToManyField(to='book.Wydanie')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezerwacji', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Nowa'), (1, 'Rozpatrzona')], default=0)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SiteUser')),
                ('wydanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Wydanie')),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('czytelnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SiteUser')),
                ('egzemplarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Egzemplarz')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczajacy_pracownik', to='user.SiteUser')),
            ],
        ),
    ]
