# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_ocena_polka_rezerwacja_wypozyczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='status',
            field=models.IntegerField(choices=[(0, 'Oczekująca'), (1, 'Zrealizowana'), (2, 'Wygasła'), (3, 'Anulowana')], default=0),
        ),
    ]
