# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
                ('stanowisko', models.CharField(max_length=150)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('imie', models.CharField(max_length=150)),
                ('nazwisko', models.CharField(max_length=150)),
                ('nr_tel', models.CharField(max_length=12)),
                ('miasto', models.CharField(max_length=250)),
                ('nr_domu', models.CharField(max_length=10)),
                ('nr_lokalu', models.CharField(max_length=10)),
            ],
        ),
    ]
